// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by cmd/tsenums from the Go enum constants; DO NOT EDIT.
// Run `make tsenums` to regenerate. These string-literal unions mirror the Go
// enums one-to-one, so a typo'd value fails type-check and Go↔TS drift is caught
// by the cmd/tsenums drift test.

export type Disposition = 'approve' | 'decline' | 'refer';

export type RunStatus = 'completed' | 'failed';

export type Environment = 'sandbox' | 'staging' | 'production';
export const ENVIRONMENTS: readonly Environment[] = ['sandbox', 'staging', 'production'] as const;

export type CaseStatus = 'needs_review' | 'in_progress' | 'completed';

export type SLAState = 'on_track' | 'due_soon' | 'overdue';

export type AgentRunStatus = 'running' | 'completed' | 'failed';

export type ModelKind = 'logistic' | 'gbm' | 'expression' | 'external';

export type PreApprovalStatus = 'active' | 'revoked';

export type MonitorOp = 'gt' | 'lt';

export type MonitorMetric = 'failure_rate' | 'refer_rate' | 'automation_rate' | 'approve_rate' | 'decline_rate' | 'avg_latency_ms' | 'volume' | 'distribution_drift';
export const MONITOR_METRICS: readonly MonitorMetric[] = ['failure_rate', 'refer_rate', 'automation_rate', 'approve_rate', 'decline_rate', 'avg_latency_ms', 'volume', 'distribution_drift'] as const;

