// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by cmd/tsenums from the Go enum constants; DO NOT EDIT.
// Run `make tsenums` to regenerate. These string-literal unions mirror the Go
// enums one-to-one, so a typo'd value fails type-check and Go↔TS drift is caught
// by the cmd/tsenums drift test.

export type Disposition = 'approve' | 'decline' | 'refer';

export type RunStatus = 'completed' | 'failed';

export type Variant = 'champion' | 'challenger';

export type NodeType = 'input' | 'rule' | 'split' | 'assignment' | 'scorecard' | 'decision_table' | '2d_matrix' | 'code' | 'ai' | 'connect' | 'predict' | 'manual_review' | 'reason' | 'output';

export type Aggregation = 'count' | 'sum';
export const AGGREGATIONS: readonly Aggregation[] = ['count', 'sum'] as const;

export type Role = 'viewer' | 'operator' | 'editor' | 'approver' | 'admin';
export const ROLES: readonly Role[] = ['viewer', 'operator', 'editor', 'approver', 'admin'] as const;

export type Scope = 'sandbox' | 'production' | '*';
export const SCOPES: readonly Scope[] = ['sandbox', 'production', '*'] as const;

export type Environment = 'sandbox' | 'staging' | 'production';
export const ENVIRONMENTS: readonly Environment[] = ['sandbox', 'staging', 'production'] as const;

export type CaseStatus = 'needs_review' | 'in_progress' | 'completed';

export type SLAState = 'on_track' | 'due_soon' | 'overdue';

export type AgentRunStatus = 'running' | 'completed' | 'failed';

export type ModelKind = 'logistic' | 'gbm' | 'expression' | 'external';

export type PreApprovalStatus = 'active' | 'revoked';

export type DeploymentRequestStatus = 'pending' | 'approved' | 'rejected';

export type MonitorOp = 'gt' | 'lt';

export type MonitorMetric = 'failure_rate' | 'refer_rate' | 'automation_rate' | 'approve_rate' | 'decline_rate' | 'avg_latency_ms' | 'volume' | 'distribution_drift';
export const MONITOR_METRICS: readonly MonitorMetric[] = ['failure_rate', 'refer_rate', 'automation_rate', 'approve_rate', 'decline_rate', 'avg_latency_ms', 'volume', 'distribution_drift'] as const;

