// SPDX-License-Identifier: AGPL-3.0-or-later
// Decision history synthesizer: ~420 decisions over ~30 days, generated by WALKING
// THE REAL SEEDED GRAPHS (walk.ts) with band-targeted inputs — every trace is the
// node path the deployed graph version actually takes for that input, every
// disposition is the flow's bound policy applied to the terminal record, and every
// model output is the registry model evaluated over the record. Volume follows a
// day/night rhythm, environments and versions follow each flow's deployments
// (challenger arms included), failures truncate at a named node with a believable
// provider error, and a few runs are left suspended at their manual-review node.

import type { Decision, Disposition, Environment, Flow, Model, Policy, NodeRecord } from '$lib/api';
import { walkGraph, applyPolicySpec } from '../walk';
import { now } from './base';

interface DecisionProfile {
  slug: string;
  envs: Environment[];
  dispositions: Disposition[];
  challenger?: { env: Environment; every: number };
  fail?: { at: number[]; node: string; error: string };
  suspendAt?: number[];
  input: (j: number, band: Disposition) => Record<string, unknown>;
}

const PROFILES: DecisionProfile[] = [
  {
    slug: 'credit-decision',
    envs: ['production', 'production', 'production', 'staging', 'sandbox'],
    dispositions: [
      'approve',
      'approve',
      'refer',
      'approve',
      'decline',
      'approve',
      'refer',
      'approve',
      'approve',
      'decline',
      'refer',
      'approve'
    ],
    challenger: { env: 'sandbox', every: 2 },
    fail: {
      at: [4, 11, 19, 30, 42],
      node: 'score',
      error: 'connector "experian" timed out after 800ms (bureau features unavailable)'
    },
    suspendAt: [1],
    input: (j, band) => {
      if (band === 'approve') {
        return {
          income: 96000 + (j % 6) * 9000,
          debt: 10000 + (j % 5) * 3000,
          revolving_balance: 1800 + (j % 4) * 700,
          credit_limit: 18000,
          delinquencies_24m: 0,
          fico_score: 748 + (j % 5) * 10,
          tenure_years: 3 + (j % 7),
          employment_stability: 0.7 + (j % 4) * 0.07
        };
      }
      if (band === 'decline') {
        return {
          income: 30000 + (j % 4) * 4000,
          debt: 24000 + (j % 4) * 2500,
          revolving_balance: 12200 + (j % 3) * 900,
          credit_limit: 15000,
          delinquencies_24m: 2 + (j % 2),
          fico_score: 582 + (j % 4) * 9,
          tenure_years: 1 + (j % 3),
          employment_stability: 0.35 + (j % 3) * 0.08
        };
      }
      return {
        income: 60000 + (j % 4) * 4000,
        debt: 26000 + (j % 4) * 2600,
        revolving_balance: 7000 + (j % 3) * 800,
        credit_limit: 15000,
        delinquencies_24m: 1,
        fico_score: 648 + (j % 4) * 7,
        tenure_years: 2 + (j % 5),
        employment_stability: 0.5 + (j % 3) * 0.1
      };
    }
  },
  {
    slug: 'aml-screening',
    envs: ['production', 'production', 'staging', 'production', 'sandbox', 'staging'],
    dispositions: [
      'approve',
      'approve',
      'refer',
      'approve',
      'approve',
      'refer',
      'approve',
      'refer',
      'approve',
      'approve',
      'refer',
      'approve',
      'approve',
      'refer'
    ],
    challenger: { env: 'staging', every: 2 },
    fail: {
      at: [23, 61],
      node: 'score',
      error: 'connector "ofac-sanctions" returned 503 (upstream maintenance)'
    },
    input: (j, band) => {
      if (band === 'refer') {
        const variant = j % 3;
        if (variant === 0) {
          // Large cross-border wire to a high-risk corridor.
          return {
            amount: 42000 + (j % 5) * 9000,
            origin_country: 'US',
            dest_country: j % 2 ? 'KY' : 'PA',
            watchlist_score: 10 + (j % 3) * 8,
            deposits_30d: 1,
            outflow_ratio: 0.5
          };
        }
        if (variant === 1) {
          // Sub-threshold structuring: only v3's code node catches it, so the
          // production champion (v2) clears these — the challenger's whole point.
          return {
            amount: 8600 + (j % 3) * 300,
            origin_country: 'US',
            dest_country: 'US',
            watchlist_score: 8,
            deposits_30d: 5 + (j % 3),
            outflow_ratio: 0.6
          };
        }
        // Confirmed watchlist hit — hard stop.
        return {
          amount: 15000 + (j % 4) * 5000,
          origin_country: 'US',
          dest_country: j % 2 ? 'AE' : 'US',
          watchlist_score: 84 + (j % 3) * 4,
          deposits_30d: 1,
          outflow_ratio: 0.3
        };
      }
      return {
        amount: 1500 + (j % 9) * 700,
        origin_country: 'US',
        dest_country: 'US',
        watchlist_score: 5 + (j % 4) * 6,
        deposits_30d: j % 3,
        outflow_ratio: 0.2 + (j % 4) * 0.1
      };
    }
  },
  {
    slug: 'card-fraud',
    envs: ['production', 'production', 'production', 'production', 'staging', 'sandbox'],
    dispositions: [
      'approve',
      'approve',
      'approve',
      'refer',
      'approve',
      'decline',
      'approve',
      'approve',
      'refer',
      'approve'
    ],
    challenger: { env: 'production', every: 7 },
    fail: {
      at: [37],
      node: 'score',
      error: 'model "fraud_score": feature "device_score" missing from payload'
    },
    input: (j, band) => {
      if (band === 'decline') {
        return {
          amount: 900 + (j % 7) * 260,
          tx_count_1h: 6 + (j % 4),
          device_score: 60 + (j % 5) * 8,
          avg_ticket: 120,
          card_present: 0,
          new_device: 0
        };
      }
      if (band === 'refer') {
        return {
          amount: 150 + (j % 5) * 40,
          tx_count_1h: 5 + (j % 3),
          device_score: 20 + (j % 4) * 9,
          avg_ticket: 120,
          card_present: 0,
          new_device: j % 2
        };
      }
      return {
        amount: 40 + (j % 8) * 35,
        tx_count_1h: j % 4,
        device_score: 12 + (j % 5) * 9,
        avg_ticket: 120,
        card_present: j % 2,
        new_device: 0
      };
    }
  },
  {
    slug: 'kyc-onboarding',
    envs: ['production', 'production', 'production', 'staging', 'sandbox'],
    dispositions: ['approve', 'approve', 'refer', 'approve', 'refer', 'approve', 'approve'],
    fail: {
      at: [13, 31],
      node: 'extract',
      error: 'agent "kyc-extract" failed: provider timeout after 30s'
    },
    suspendAt: [2],
    input: (j, band) => {
      if (band === 'refer') {
        return j % 2
          ? { doc_score: 82 + (j % 3) * 3, pep_match: 1 }
          : { doc_score: 42 + (j % 4) * 4, pep_match: 0 };
      }
      return { doc_score: 72 + (j % 6) * 4, pep_match: 0 };
    }
  },
  {
    slug: 'dispute-triage',
    envs: ['production', 'production', 'production', 'staging', 'sandbox'],
    dispositions: ['refer', 'approve', 'refer', 'refer', 'approve', 'refer', 'approve', 'refer'],
    fail: {
      at: [17],
      node: 'summary',
      error: 'agent "dispute-summarizer" failed: rate limited (429)'
    },
    input: (j, band) => {
      const reason = ['product_not_received', 'duplicate', 'quality', 'fraud'][j % 4];
      if (band === 'refer') {
        return { amount: 640 + (j % 5) * 120, reason_code: reason };
      }
      return { amount: 60 + (j % 6) * 55, reason_code: reason };
    }
  },
  {
    slug: 'merchant-onboarding',
    envs: ['staging', 'sandbox', 'staging'],
    dispositions: ['approve', 'refer', 'approve', 'refer', 'approve', 'refer'],
    fail: {
      at: [9],
      node: 'score',
      error: 'connector "lexisnexis-kyb" timed out after 1200ms'
    },
    input: (j, band) => {
      if (band === 'refer') {
        return j % 2
          ? { monthly_volume: 150000 + (j % 3) * 20000, mcc_risk: 52, international: 1 }
          : {
              monthly_volume: 30000 + (j % 4) * 10000,
              mcc_risk: 74 + (j % 3) * 6,
              international: 0
            };
      }
      return {
        monthly_volume: 20000 + (j % 6) * 9000,
        mcc_risk: 20 + (j % 3) * 8,
        international: j % 2
      };
    }
  },
  {
    slug: 'collections-hardship',
    envs: ['production', 'production', 'production', 'staging', 'sandbox'],
    dispositions: [
      'approve',
      'refer',
      'decline',
      'approve',
      'approve',
      'decline',
      'refer',
      'approve'
    ],
    input: (j, band) => {
      if (band === 'refer') {
        return {
          prior_income: 5200,
          current_income: 2300 + (j % 3) * 200,
          missed_payments_6m: 3 + (j % 2),
          medical_event: j % 2,
          tenure_years: 4 + (j % 3),
          balance_usd: 12000 + (j % 3) * 2500
        };
      }
      if (band === 'decline') {
        return {
          prior_income: 5200,
          current_income: 4700 + (j % 3) * 100,
          missed_payments_6m: 1,
          medical_event: 0,
          tenure_years: 5 + (j % 3),
          balance_usd: 4200
        };
      }
      return {
        prior_income: 5200,
        current_income: 3300 + (j % 3) * 100,
        missed_payments_6m: 2,
        medical_event: 0,
        tenure_years: 1 + (j % 2),
        balance_usd: 6000 + (j % 3) * 1500
      };
    }
  },
  {
    slug: 'claim-triage',
    envs: ['production', 'production', 'production', 'staging', 'sandbox'],
    dispositions: ['approve', 'refer', 'approve', 'decline', 'approve', 'refer', 'approve'],
    fail: {
      at: [6],
      node: 'score',
      error: 'model "claim_fraud": feature "prior_claims_24m" missing from payload'
    },
    input: (j, band) => {
      if (band === 'decline') {
        return {
          amount: 500 + (j % 4) * 200,
          coverage_limit: 3000,
          policy_active: 0,
          prior_claims_24m: j % 3,
          days_since_policy_start: 300
        };
      }
      if (band === 'refer') {
        if (j % 2) {
          // Abuse pattern: repeat claimant on a young policy at the coverage limit.
          const coverage = 2000 + (j % 3) * 500;
          return {
            amount: Math.round(coverage * 0.9),
            coverage_limit: coverage,
            policy_active: 1,
            prior_claims_24m: 2 + (j % 2),
            days_since_policy_start: 10 + (j % 3) * 15
          };
        }
        // High severity relative to coverage, no abuse signals.
        return {
          amount: 1900 + (j % 4) * 300,
          coverage_limit: 3600,
          policy_active: 1,
          prior_claims_24m: 1,
          days_since_policy_start: 150 + (j % 3) * 50
        };
      }
      if (j % 2) {
        // Low-value first claim → fast-track.
        return {
          amount: 60 + (j % 4) * 40,
          coverage_limit: 3000 + (j % 3) * 1000,
          policy_active: 1,
          prior_claims_24m: 0,
          days_since_policy_start: 200 + (j % 5) * 60
        };
      }
      return {
        amount: 380 + (j % 4) * 60,
        coverage_limit: 2400 + (j % 3) * 800,
        policy_active: 1,
        prior_claims_24m: 1,
        days_since_policy_start: 220 + (j % 4) * 40
      };
    }
  },
  {
    slug: 'payout-risk',
    envs: ['production', 'production', 'staging', 'production', 'sandbox'],
    dispositions: [
      'approve',
      'approve',
      'refer',
      'approve',
      'decline',
      'approve',
      'approve',
      'refer'
    ],
    fail: {
      at: [11],
      node: 'ledger',
      error: 'connector "core-banking" refused connection (pool exhausted)'
    },
    suspendAt: [1],
    input: (j, band) => {
      if (band === 'decline') {
        return {
          amount: 14000 + (j % 3) * 2000,
          avg_payout_30d: 4000,
          payouts_24h: 4 + (j % 3),
          account_age_days: 6 + (j % 3) * 7,
          chargeback_rate: 0.02
        };
      }
      if (band === 'refer') {
        return {
          amount: 12000 + (j % 4) * 2500,
          avg_payout_30d: 6000,
          payouts_24h: 3,
          account_age_days: 180 + (j % 3) * 30,
          chargeback_rate: 0.008 + (j % 2) * 0.004
        };
      }
      return {
        amount: 1500 + (j % 5) * 400,
        avg_payout_30d: 2600,
        payouts_24h: 1 + (j % 2),
        account_age_days: 220 + (j % 4) * 40,
        chargeback_rate: 0.002 + (j % 3) * 0.002
      };
    }
  },
  {
    slug: 'limit-increase',
    envs: ['sandbox', 'staging', 'sandbox'],
    dispositions: ['approve', 'refer', 'approve', 'decline', 'approve', 'refer'],
    input: (j, band) => {
      if (band === 'decline') {
        return {
          income: 40000 + (j % 3) * 3000,
          debt: 20000 + (j % 3) * 2000,
          revolving_balance: 9800 + (j % 2) * 600,
          credit_limit: 12000,
          delinquencies_24m: 1 + (j % 2),
          fico_score: 636 + (j % 3) * 4
        };
      }
      if (band === 'refer') {
        return {
          income: 70000 + (j % 3) * 4000,
          debt: 24000 + (j % 3) * 2000,
          revolving_balance: 7900 + (j % 3) * 300,
          credit_limit: 12000,
          delinquencies_24m: 0,
          fico_score: 682 + (j % 3) * 6
        };
      }
      return {
        income: 95000 + (j % 5) * 8000,
        debt: 9000 + (j % 4) * 2000,
        revolving_balance: 1500 + (j % 3) * 500,
        credit_limit: 12000,
        delinquencies_24m: 0,
        fico_score: 758 + (j % 4) * 8
      };
    }
  }
];

// Traffic mix: one 30-slot rotation ≈ the fleet's relative volumes (fraud and AML
// dominate, onboarding/servicing flows trickle). 14 rotations ⇒ 420 decisions.
const PATTERN = [
  'card-fraud',
  'aml-screening',
  'credit-decision',
  'card-fraud',
  'dispute-triage',
  'aml-screening',
  'kyc-onboarding',
  'card-fraud',
  'credit-decision',
  'payout-risk',
  'aml-screening',
  'card-fraud',
  'merchant-onboarding',
  'credit-decision',
  'aml-screening',
  'card-fraud',
  'dispute-triage',
  'kyc-onboarding',
  'payout-risk',
  'collections-hardship',
  'card-fraud',
  'aml-screening',
  'credit-decision',
  'claim-triage',
  'card-fraud',
  'aml-screening',
  'limit-increase',
  'dispute-triage',
  'kyc-onboarding',
  'card-fraud'
];
const ROTATIONS = 14;

// Per-node latency contributions (ms): connectors and LLM calls dominate, pure
// compute is cheap — so a flow's duration tracks the depth and shape of the graph
// it actually walked.
const NODE_COST = new Map<string, number>([
  ['input', 2],
  ['assignment', 3],
  ['rule', 3],
  ['scorecard', 4],
  ['decision_table', 4],
  ['2d_matrix', 4],
  ['code', 5],
  ['reason', 2],
  ['split', 2],
  ['output', 3],
  ['predict', 12],
  ['connect', 85],
  ['ai', 190],
  ['manual_review', 6]
]);

function traceDuration(nodes: NodeRecord[], jitter: number): number {
  const base = nodes.reduce((sum, n) => sum + (NODE_COST.get(n.type) ?? 3), 0);
  return base + jitter;
}

function deployedVersion(flow: Flow, env: Environment, challenger: boolean): number {
  const dep = new Map(Object.entries(flow.deployments ?? {})).get(env);
  if (!dep) throw new Error(`seed: ${flow.slug} has no ${env} deployment`);
  if (challenger) {
    if (!dep.challenger_version) throw new Error(`seed: ${flow.slug} has no ${env} challenger`);
    return dep.challenger_version;
  }
  return dep.version;
}

// seedDecisions walks the deployed graphs with the profiles above. Throws (fails
// the whole seed, loudly) if any crafted input fails to complete its walk — a seed
// bug, never something to paper over.
export function seedDecisions(flows: Flow[], models: Model[], policies: Policy[]): Decision[] {
  const flowsBySlug = new Map(flows.map((f) => [f.slug, f]));
  const policyBySlug = new Map(policies.map((p) => [p.flow_slug, p]));
  const counters = new Map<string, number>();
  const out: Decision[] = [];
  let hoursAgo = 1.2;

  const total = PATTERN.length * ROTATIONS;
  for (let i = 1; i <= total; i++) {
    const slug = PATTERN[(i - 1) % PATTERN.length];
    const profile = PROFILES.find((p) => p.slug === slug);
    const flow = flowsBySlug.get(slug);
    if (!profile || !flow) throw new Error(`seed: unknown flow ${slug}`);
    const j = counters.get(slug) ?? 0;
    counters.set(slug, j + 1);

    const env = profile.envs[j % profile.envs.length];
    const challenger =
      profile.challenger !== undefined &&
      env === profile.challenger.env &&
      j % profile.challenger.every === 0;
    const version = deployedVersion(flow, env, challenger);
    const graph = flow.versions.find((v) => v.version === version)?.graph;
    if (!graph) throw new Error(`seed: ${slug} v${version} missing`);

    const suspend = profile.suspendAt?.includes(j) ?? false;
    const fail = !suspend && (profile.fail?.at.includes(j) ?? false);
    const band = suspend ? 'refer' : profile.dispositions[j % profile.dispositions.length];
    const input = profile.input(j, band);
    const run = walkGraph(graph, input, models);
    if (run.status !== 'completed') {
      throw new Error(`seed: ${slug} v${version} j=${j} did not complete: ${run.error}`);
    }

    const startedMs = now.getTime() - hoursAgo * 3600_000;
    const hourOfDay = new Date(startedMs).getHours();
    const night = hourOfDay < 7 || hourOfDay >= 21;
    hoursAgo += night ? 3.4 + (i % 5) * 0.8 : 0.75 + (i % 4) * 0.35;
    const startedAt = new Date(startedMs).toISOString();

    const decision: Decision = {
      decision_id: `dec_${i}`,
      flow_id: flow.flow_id,
      slug,
      version,
      environment: env,
      variant: challenger ? 'challenger' : 'champion',
      status: 'completed',
      data: run.data,
      output: run.output,
      reason_codes: run.reasonCodes,
      nodes: run.nodes,
      started_at: startedAt
    };

    if (fail && profile.fail) {
      // A believable mid-run infrastructure failure: the trace ends where the
      // named node would have run, the request payload is all that was recorded.
      const idx = run.nodes.findIndex((n) => n.node_id === profile.fail?.node);
      if (idx < 0) throw new Error(`seed: fail node ${profile.fail.node} not on ${slug}'s path`);
      const walked = run.nodes.slice(0, idx);
      const duration = traceDuration(walked, 800 + (i % 5) * 40);
      decision.status = 'failed';
      decision.data = input;
      decision.output = {};
      decision.reason_codes = [];
      decision.nodes = walked;
      decision.error = profile.fail.error;
      decision.ended_at = new Date(startedMs + duration).toISOString();
      decision.duration_ms = duration;
    } else if (suspend) {
      // Paused at the durable human task: the trace ends AT the manual-review
      // node, no terminal output or disposition yet — Resume completes it.
      const idx = run.nodes.findIndex((n) => n.type === 'manual_review');
      const reviewNode = run.nodes.at(idx);
      if (idx < 0 || !reviewNode) {
        throw new Error(`seed: no manual_review on ${slug}'s refer path`);
      }
      const walked = [...run.nodes.slice(0, idx), { ...reviewNode, output: { suspended: true } }];
      decision.status = 'suspended';
      decision.output = {};
      decision.nodes = walked;
      decision.policy_id = policyBySlug.get(slug)?.policy_id;
    } else {
      const policy = policyBySlug.get(slug);
      const spec = policy?.versions.find((v) => v.version === policy.latest)?.spec;
      if (!policy || !spec) throw new Error(`seed: no policy bound to ${slug}`);
      const banded = applyPolicySpec(spec, run.data, run.reasonCodes);
      const duration = traceDuration(run.nodes, (i % 6) * 7 + (i % 11));
      decision.disposition = banded.disposition;
      decision.disposition_reason = banded.reason;
      decision.policy_id = policy.policy_id;
      decision.policy_version = policy.latest;
      decision.ended_at = new Date(startedMs + duration).toISOString();
      decision.duration_ms = duration;
    }

    out.push(decision);
  }
  return out;
}
