{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intraktible.fullname" . }}-secrets
  labels: {{- include "intraktible.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.data }}
{{- if $v }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- end }}
