// SPDX-License-Identifier: AGPL-3.0-or-later

// Command tsenums generates the TypeScript string-literal unions in
// web/src/lib/enums.generated.ts from the Go enum constants — the single source of
// truth. The Go consts are imported and stringified directly, so the TS values
// cannot drift from the Go ones: change a Go const and the generated TS changes;
// add/remove one and the generated TS (and the drift-check test) flag it. Run via
// `make tsenums`; the committed output is verified up-to-date in CI by the test in
// this package.
package main

import (
	"fmt"
	"os"
	"strings"

	agentdomain "github.com/e6qu/intraktible/agent-manager/domain"
	casedomain "github.com/e6qu/intraktible/case-manager/domain"
	ctxdomain "github.com/e6qu/intraktible/context-layer/domain"
	dedomain "github.com/e6qu/intraktible/decision-engine/domain"
	"github.com/e6qu/intraktible/decision-engine/events"
	"github.com/e6qu/intraktible/decision-engine/flows"
	"github.com/e6qu/intraktible/decision-engine/models"
	"github.com/e6qu/intraktible/decision-engine/monitor"
	"github.com/e6qu/intraktible/decision-engine/policy"
	"github.com/e6qu/intraktible/decision-engine/preapproval"
	"github.com/e6qu/intraktible/platform/auth"
)

// tsEnum is one generated union: its TS type name, an optional runtime array name
// (empty = type only), and the ordered values sourced from the Go consts.
type tsEnum struct {
	typeName  string
	arrayName string
	values    []string
}

// enums is the registry. Each value list references the REAL Go const, so the
// generated TS is correct by construction. Only enums with a clean, exported Go
// const set are here; composite/UI-only unions (DecisionStatus, BatchStatus) stay
// hand-defined in api.ts.
var enums = []tsEnum{
	{"Disposition", "", strs(policy.Approve, policy.Decline, policy.Refer)},
	{"RunStatus", "", strs(dedomain.StatusCompleted, dedomain.StatusFailed)},
	{"Variant", "", strs(dedomain.VariantChampion, dedomain.VariantChallenger)},
	{"NodeType", "", strs(
		events.NodeInput, events.NodeRule, events.NodeSplit, events.NodeAssignment,
		events.NodeScorecard, events.NodeDecisionTable, events.NodeMatrix2D, events.NodeCode,
		events.NodeAI, events.NodeConnect, events.NodePredict, events.NodeManualReview,
		events.NodeReason, events.NodeOutput,
	)},
	{"Aggregation", "AGGREGATIONS", strs(ctxdomain.AggCount, ctxdomain.AggSum)},
	{"Role", "ROLES", strs(auth.RoleViewer, auth.RoleOperator, auth.RoleEditor, auth.RoleApprover, auth.RoleAdmin)},
	{"Scope", "SCOPES", strs(auth.Sandbox, auth.Production, auth.ScopeAll)},
	{"Environment", "ENVIRONMENTS", strs(dedomain.EnvSandbox, dedomain.EnvStaging, dedomain.EnvProduction)},
	{"CaseStatus", "", strs(casedomain.StatusNeedsReview, casedomain.StatusInProgress, casedomain.StatusCompleted)},
	{"SLAState", "", strs(casedomain.SLAOnTrack, casedomain.SLADueSoon, casedomain.SLAOverdue)},
	{"AgentRunStatus", "", strs(agentdomain.RunRunning, agentdomain.RunCompleted, agentdomain.RunFailed)},
	{"ModelKind", "", strs(models.KindLogistic, models.KindGBM, models.KindExpression, models.KindExternal)},
	{"PreApprovalStatus", "", strs(preapproval.StatusActive, preapproval.StatusRevoked)},
	{"DeploymentRequestStatus", "", strs(flows.RequestPending, flows.RequestApproved, flows.RequestRejected)},
	{"MonitorOp", "", strs(monitor.OpGreaterThan, monitor.OpLessThan)},
	{"MonitorMetric", "MONITOR_METRICS", strs(
		monitor.MetricFailureRate, monitor.MetricReferRate, monitor.MetricAutomationRate,
		monitor.MetricApproveRate, monitor.MetricDeclineRate, monitor.MetricAvgLatencyMS,
		monitor.MetricVolume, monitor.MetricDistributionDrift,
		monitor.MetricDistributionDriftPSI, monitor.MetricDistributionDriftKL,
	)},
}

// strs stringifies named-string enum constants of any kind into a value slice.
func strs[T ~string](vs ...T) []string {
	out := make([]string, len(vs))
	for i, v := range vs {
		out[i] = string(v)
	}
	return out
}

const outPath = "web/src/lib/enums.generated.ts"

// Generate renders the enums.generated.ts contents. It is pure (no I/O) so the
// drift-check test can compare it to the committed file.
func Generate() string {
	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
	b.WriteString("// Code generated by cmd/tsenums from the Go enum constants; DO NOT EDIT.\n")
	b.WriteString("// Run `make tsenums` to regenerate. These string-literal unions mirror the Go\n")
	b.WriteString("// enums one-to-one, so a typo'd value fails type-check and Go↔TS drift is caught\n")
	b.WriteString("// by the cmd/tsenums drift test.\n\n")
	for _, e := range enums {
		quoted := make([]string, len(e.values))
		for i, v := range e.values {
			quoted[i] = "'" + v + "'"
		}
		fmt.Fprintf(&b, "export type %s = %s;\n", e.typeName, strings.Join(quoted, " | "))
		if e.arrayName != "" {
			fmt.Fprintf(&b, "export const %s: readonly %s[] = [%s] as const;\n", e.arrayName, e.typeName, strings.Join(quoted, ", "))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func main() {
	if err := os.WriteFile(outPath, []byte(Generate()), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "tsenums:", err)
		os.Exit(1)
	}
	fmt.Println("wrote", outPath)
}
