// SPDX-License-Identifier: AGPL-3.0-or-later

package domain_test

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/e6qu/intraktible/decision-engine/domain"
	"github.com/e6qu/intraktible/decision-engine/events"
)

// parityFixturesPath is where the differential-parity battery lands, relative to
// this package: the demo's vitest (web/src/lib/demo/engine-parity.test.ts) replays
// every case through the in-browser walker and asserts the demo behaves EXACTLY
// like this engine — status, final output, node-id trace, per-node outputs, reason
// codes and failure messages.
const parityFixturesPath = "../../web/src/lib/demo/engine-parity-fixtures.json"

// parityReadme is embedded at the top of the fixture file so the exclusions are
// documented next to the data they scope.
var parityReadme = []string{
	"GENERATED by decision-engine/domain/parity_fixtures_test.go — DO NOT EDIT.",
	"Regenerate: UPDATE_PARITY_FIXTURES=1 go test ./decision-engine/domain -run TestEngineParityFixtures",
	"Every expectation below is computed by the REAL engine (domain.Execute). The vitest",
	"web/src/lib/demo/engine-parity.test.ts replays each case through the demo walker",
	"(web/src/lib/demo/walk.ts) and asserts behavioral parity: status, final output,",
	"trace node-id sequence, per-node outputs, reason codes, failed node, and (for",
	"failures) that the demo error CONTAINS error_contains (the Go error with the",
	"expr-lang position/snippet suffix stripped).",
	"Numbers are compared after a JSON round-trip, so Go int/float distinctions that",
	"JSON erases (int 1 vs float64 1) are equal by design; float64 arithmetic is",
	"bit-identical between Go and JS, so values like 0.30000000000000004 match exactly.",
	"DOCUMENTED EXCLUSIONS (not fixtured):",
	"1. code nodes: Go runs Starlark; the demo runs the shared assignment subset",
	"   (`name = expr` lines, data['field'] reads, # comments). Control flow, def,",
	"   //, **, negative modulo (Python floors, JS truncates) and Starlark's own",
	"   error texts (beyond the empty-code guard) are outside the shared subset.",
	"2. predict/connect/ai: fixtures inject PRE-RESOLVED buckets (the Go shell's",
	"   seam) which both engines echo identically. Missing-provider failures are",
	"   not fixtured — the demo always has its in-browser providers.",
	"3. expr-lang features beyond the demo grammar (builtins, `in`, ranges, string",
	"   repeat, closures) are not fixtured.",
	"4. runtime-format type errors on deep-path values (e.g. `nested.b + 1` →",
	"   'invalid operation: <nil> + int') are not fixtured; the demo reports",
	"   checker-format messages for those. Deep-path reads, equality and ?? ARE",
	"   fixtured (they succeed identically).",
	"5. demo-authoring dialect config forms (split edges carrying condition",
	"   expressions, output-node assignments, manual_review literal configs, code",
	"   `source` DSL) are demo sugar the real engine rejects; the parity surface is",
	"   the real engine's config forms, which the demo executes with Go semantics.",
	"6. suspended-run resume is not fixtured (the demo resumes through its store",
	"   shell); the suspend state itself IS fixtured (record + case fields).",
}

type parityCase struct {
	name  string
	graph events.Graph
	input string
	want  domain.RunStatus
}

type parityTraceNode struct {
	NodeID string `json:"node_id"`
	Type   string `json:"type"`
	Output any    `json:"output"`
}

type paritySuspend struct {
	NodeID      string         `json:"node_id"`
	Record      map[string]any `json:"record"`
	CompanyName string         `json:"company_name"`
	CaseType    string         `json:"case_type"`
	SLADays     int            `json:"sla_days"`
}

type parityExpect struct {
	Status        string            `json:"status"`
	Output        map[string]any    `json:"output,omitempty"`
	ReasonCodes   []any             `json:"reason_codes,omitempty"`
	Trace         []parityTraceNode `json:"trace"`
	FailedNode    string            `json:"failed_node,omitempty"`
	Error         string            `json:"error,omitempty"`
	ErrorContains string            `json:"error_contains,omitempty"`
	Suspend       *paritySuspend    `json:"suspend,omitempty"`
}

type parityCaseJSON struct {
	Name   string         `json:"name"`
	Graph  events.Graph   `json:"graph"`
	Input  map[string]any `json:"input"`
	Expect parityExpect   `json:"expect"`
}

type parityFile struct {
	Readme []string         `json:"_readme"`
	Cases  []parityCaseJSON `json:"cases"`
}

func parNode(id string, t events.NodeType, config string) events.Node {
	n := events.Node{ID: id, Type: t}
	if config != "" {
		n.Config = json.RawMessage(config)
	}
	return n
}

// parChain builds in -> nodes... -> out with unconditional edges; the first node
// must be the input and the last the output.
func parChain(nodes ...events.Node) events.Graph {
	g := events.Graph{Nodes: nodes}
	for i := 0; i+1 < len(nodes); i++ {
		g.Edges = append(g.Edges, events.Edge{From: nodes[i].ID, To: nodes[i+1].ID})
	}
	return g
}

// parLine is the common one-worker shape: input -> mid -> output(outCfg).
func parLine(mid events.Node, outCfg string) events.Graph {
	return parChain(parNode("in", events.NodeInput, ""), mid, parNode("out", events.NodeOutput, outCfg))
}

// parInput is the standard input record most cases share, parsed from JSON so
// every number is a float64 — exactly what the real decide path (and the browser)
// sees on the wire.
const parInput = `{"amount": 100, "flag": true, "name": "alice", "nested": {"a": 1}, "nothing": null}`

// parityPositionSuffix strips expr-lang's trailing position + snippet (e.g.
// ` (1:8)\n | amount % 3\n | .......^`) so error_contains carries the stable core
// message the demo must reproduce.
var parityPositionSuffix = regexp.MustCompile(`(?s)\s\(\d+:\d+\)(\n \|.*)?\z`)

func parityCases() []parityCase {
	asn := func(id string, pairs ...string) events.Node {
		type a struct {
			Target string `json:"target"`
			Expr   string `json:"expr"`
		}
		var cfg struct {
			Assignments []a `json:"assignments"`
		}
		for i := 0; i+1 < len(pairs); i += 2 {
			cfg.Assignments = append(cfg.Assignments, a{pairs[i], pairs[i+1]})
		}
		b, _ := json.Marshal(cfg)
		return parNode(id, events.NodeAssignment, string(b))
	}

	return []parityCase{
		// --- input / output --------------------------------------------------------
		{
			name:  "output-passthrough-whole-record",
			graph: parChain(parNode("in", events.NodeInput, ""), parNode("out", events.NodeOutput, "")),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "output-fields-filter-with-missing-field-null",
			graph: parLine(
				asn("calc", "decision", "amount >= 100 ? 'approve' : 'review'", "score", "amount / 10"),
				`{"fields":["decision","score","missing"]}`,
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "output-fields-always-surface-reason-codes",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("rc", events.NodeReason, `{"reasons":[{"when":"amount >= 100","code":"HIGH_AMOUNT","description":"Amount above threshold"}]}`),
				asn("calc", "decision", "'review'"),
				parNode("out", events.NodeOutput, `{"fields":["decision"]}`),
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "output-no-fields-includes-accumulated-reason-codes",
			graph: parLine(
				parNode("rc", events.NodeReason, `{"reasons":[{"when":"amount >= 100","code":"HIGH_AMOUNT","description":"Amount above threshold"}]}`),
				"",
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},

		// --- assignment ------------------------------------------------------------
		{
			name: "assignment-arithmetic-battery",
			graph: parLine(asn("calc",
				"sum", "amount + 2",
				"prod", "amount * 1.5",
				"quot", "amount / 8",
				"intdiv", "10 / 4",
				"mod", "7 % 2",
				"pow", "2 ** 3",
				"prec", "amount + 1 * 2",
				"paren", "(amount + 1) * 2",
				"neg", "-amount",
				"floats", "0.1 + 0.2",
			), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "assignment-chained-targets",
			graph: parLine(asn("calc",
				"a", "amount / 4",
				"b", "a * 2",
				"c", "b + a",
			), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "assignment-strings-and-ternaries",
			graph: parLine(asn("calc",
				"greeting", "name + '!'",
				"band", "amount >= 100 ? 'high' : 'low'",
				"size", "amount >= 1000 ? 'xl' : (amount >= 100 ? 'l' : 's')",
				"empty", "'' + name",
			), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "assignment-boolean-battery",
			graph: parLine(asn("calc",
				"eq", "amount == 100",
				"eqf", "amount == 100.0",
				"neq", "name != 'bob'",
				"both", "amount > 50 && amount < 200",
				"either", "amount > 500 || flag",
				"notf", "!flag",
				"nil_eq", "nothing == nil",
				"nil_ne", "amount == nil",
				"deep_eq", "nested.b == 1",
				"strcmp", "name < 'bob'",
			), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "assignment-nil-coalesce-and-deep-paths",
			graph: parLine(asn("calc",
				"d1", "nested.b ?? 7",
				"d2", "nothing ?? 5",
				"deep", "nested.a + 1",
				"missing_deep", "nested.b",
				"deep_nil", "nested.b == nil",
			), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "assignment-division-by-zero-infinity-trace-null",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				asn("calc", "x", "amount / 0"),
				asn("chk", "huge", "x > 1000000"),
				parNode("out", events.NodeOutput, `{"fields":["huge"]}`),
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "assignment-integer-threading-through-context",
			graph: parLine(asn("calc",
				"x", "7 % 2",
				"y", "x + 1",
				"z", "y % 2",
				"w", "y / 2",
			), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "fail-assignment-unknown-name",
			graph: parLine(asn("calc", "x", "missing_field + 1"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-unknown-name-in-unused-ternary-branch",
			graph: parLine(asn("calc", "x", "flag ? 1 : ghost + 1"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-string-plus-number",
			graph: parLine(asn("calc", "x", "'a' + 1"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-float-modulo",
			graph: parLine(asn("calc", "x", "amount % 3"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-number-plus-bool",
			graph: parLine(asn("calc", "x", "1 + true"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-and-non-bool",
			graph: parLine(asn("calc", "x", "flag && 1"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-ternary-non-bool-condition",
			graph: parLine(asn("calc", "x", "amount ? 1 : 2"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-not-non-bool",
			graph: parLine(asn("calc", "x", "!amount"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-negate-string",
			graph: parLine(asn("calc", "x", "-name"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-empty-expression",
			graph: parLine(asn("calc", "x", ""), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-null-root-arithmetic",
			graph: parLine(asn("calc", "x", "nothing + 1"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-assignment-compare-number-to-string",
			graph: parLine(asn("calc", "x", "amount > '50'"), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- rule --------------------------------------------------------------
		{
			name: "rule-cascade-later-rules-see-earlier-writes",
			graph: parLine(parNode("r", events.NodeRule, `{"rules":[
				{"when":"amount > 50","then":[{"target":"base","expr":"amount * 2"}]},
				{"when":"base > 150","then":[{"target":"tier","expr":"'gold'"},{"target":"bonus","expr":"base / 4"}]},
				{"when":"amount > 100000","then":[{"target":"never","expr":"1"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "rule-no-match-empty-output",
			graph: parLine(parNode("r", events.NodeRule, `{"rules":[
				{"when":"amount > 100000","then":[{"target":"x","expr":"1"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "fail-rule-condition-not-boolean",
			graph: parLine(parNode("r", events.NodeRule, `{"rules":[{"when":"amount","then":[{"target":"x","expr":"1"}]}]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-rule-condition-unknown-name",
			graph: parLine(parNode("r", events.NodeRule, `{"rules":[
				{"when":"amount > 0","then":[{"target":"x","expr":"1"}]},
				{"when":"ghost > 1","then":[{"target":"y","expr":"2"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-rule-then-assignment-error",
			graph: parLine(parNode("r", events.NodeRule, `{"rules":[{"when":"amount > 0","then":[{"target":"x","expr":"amount % 3"}]}]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-rule-empty-when",
			graph: parLine(parNode("r", events.NodeRule, `{"rules":[{"when":"","then":[{"target":"x","expr":"1"}]}]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- split ---------------------------------------------------------------
		{
			name:  "split-yes-branch",
			graph: paritySplitGraph("amount >= 100", true),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "split-no-branch",
			graph: paritySplitGraph("amount >= 1000", true),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "fail-split-missing-branch-edge",
			graph: paritySplitGraph("amount >= 1000", false),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-split-condition-unknown-name",
			graph: paritySplitGraph("ghost > 1", true),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-split-condition-not-boolean",
			graph: paritySplitGraph("amount + 1", true),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- scorecard -------------------------------------------------------------
		{
			name: "scorecard-weighted-sum-custom-output",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("sc", events.NodeScorecard, `{"output":"risk_score","factors":[
					{"when":"amount >= 100","weight":30},
					{"when":"flag","weight":12.5},
					{"when":"name == 'bob'","weight":100},
					{"when":"amount < 1000","weight":-7.5}
				]}`),
				asn("calc", "scaled", "risk_score * 2"),
				parNode("out", events.NodeOutput, ""),
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "scorecard-default-output-no-factor-matches",
			graph: parLine(parNode("sc", events.NodeScorecard, `{"factors":[
				{"when":"amount > 100000","weight":30}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "fail-scorecard-factor-condition-error",
			graph: parLine(parNode("sc", events.NodeScorecard, `{"factors":[
				{"when":"amount >= 100","weight":30},
				{"when":"ghost > 0","weight":10}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-scorecard-empty-when",
			graph: parLine(parNode("sc", events.NodeScorecard, `{"factors":[{"weight":30}]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- decision table ----------------------------------------------------------
		{
			name: "table-first-hit-chained-row-outputs",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"first","rows":[
				{"when":"amount > 500","outputs":[{"target":"fee","expr":"0"}]},
				{"when":"amount >= 100","outputs":[{"target":"fee","expr":"amount * 0.1"},{"target":"total","expr":"amount + fee"}]},
				{"when":"amount >= 0","outputs":[{"target":"fee","expr":"999"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "table-first-no-match-empty-output",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"rows":[
				{"when":"amount > 100000","outputs":[{"target":"x","expr":"1"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "table-unique-single-match",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"unique","rows":[
				{"when":"amount < 100","outputs":[{"target":"band","expr":"'low'"}]},
				{"when":"amount >= 100","outputs":[{"target":"band","expr":"'high'"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "fail-table-unique-conflict",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"unique","rows":[
				{"when":"amount > 0","outputs":[{"target":"band","expr":"'a'"}]},
				{"when":"amount > 1","outputs":[{"target":"band","expr":"'b'"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "table-any-identical-outputs",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"any","rows":[
				{"when":"amount >= 100","outputs":[{"target":"band","expr":"'high'"}]},
				{"when":"flag","outputs":[{"target":"band","expr":"'high'"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "fail-table-any-conflicting-outputs",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"any","rows":[
				{"when":"amount >= 100","outputs":[{"target":"band","expr":"'high'"}]},
				{"when":"flag","outputs":[{"target":"band","expr":"'low'"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "table-rule-order-collects-lists-per-target",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"rule_order","rows":[
				{"when":"amount > 0","outputs":[{"target":"codes","expr":"'A'"}]},
				{"when":"amount > 100000","outputs":[{"target":"codes","expr":"'B'"}]},
				{"when":"flag","outputs":[{"target":"codes","expr":"'C'"},{"target":"hint","expr":"2"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "table-collect-sum",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"collect","aggregate":"sum","rows":[
				{"when":"amount > 0","outputs":[{"target":"adder","expr":"amount * 0.1"}]},
				{"when":"flag","outputs":[{"target":"adder","expr":"5"}]},
				{"when":"amount > 100000","outputs":[{"target":"adder","expr":"999"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "table-collect-min-max-count",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("dtmin", events.NodeDecisionTable, `{"hit":"collect","aggregate":"min","rows":[
					{"when":"amount > 0","outputs":[{"target":"lo","expr":"amount / 4"}]},
					{"when":"flag","outputs":[{"target":"lo","expr":"7"}]}
				]}`),
				parNode("dtmax", events.NodeDecisionTable, `{"hit":"collect","aggregate":"max","rows":[
					{"when":"amount > 0","outputs":[{"target":"hi","expr":"amount / 4"}]},
					{"when":"flag","outputs":[{"target":"hi","expr":"7"}]}
				]}`),
				parNode("dtcount", events.NodeDecisionTable, `{"hit":"collect","aggregate":"count","rows":[
					{"when":"amount > 0","outputs":[{"target":"n","expr":"1"}]},
					{"when":"flag","outputs":[{"target":"n","expr":"1"}]}
				]}`),
				parNode("out", events.NodeOutput, ""),
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "table-collect-default-keeps-list",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"collect","rows":[
				{"when":"amount > 0","outputs":[{"target":"vals","expr":"1"}]},
				{"when":"flag","outputs":[{"target":"vals","expr":"'two'"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "fail-table-collect-sum-non-numeric",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"collect","aggregate":"sum","rows":[
				{"when":"amount > 0","outputs":[{"target":"v","expr":"'high'"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-table-collect-non-finite",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"collect","aggregate":"sum","rows":[
				{"when":"amount > 0","outputs":[{"target":"v","expr":"amount / 0"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-table-unknown-hit-policy",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"best","rows":[
				{"when":"amount > 0","outputs":[{"target":"x","expr":"1"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "table-legacy-mode-all-last-write-wins",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"mode":"all","rows":[
				{"when":"amount > 0","outputs":[{"target":"x","expr":"1"},{"target":"note","expr":"'first'"}]},
				{"when":"x == 1","outputs":[{"target":"x","expr":"2"},{"target":"y","expr":"x + 10"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "fail-table-rows-are-isolated-from-each-other",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"hit":"rule_order","rows":[
				{"when":"amount > 0","outputs":[{"target":"x","expr":"1"}]},
				{"when":"x == 1","outputs":[{"target":"y","expr":"2"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-table-row-output-error",
			graph: parLine(parNode("dt", events.NodeDecisionTable, `{"rows":[
				{"when":"amount > 0","outputs":[{"target":"x","expr":"amount % 3"}]}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- 2d matrix -----------------------------------------------------------
		{
			name: "matrix-cell-select-custom-output",
			graph: parLine(parNode("mx", events.NodeMatrix2D, `{"output":"action","rows":[
				{"when":"amount >= 1000"},{"when":"amount >= 100"},{"when":"amount < 100"}
			],"cols":[{"when":"flag"},{"when":"!flag"}],"cells":[
				["hold","hold"],["review","release"],["release","release"]
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "matrix-default-output-key",
			graph: parLine(parNode("mx", events.NodeMatrix2D, `{"rows":[{"when":"amount >= 0"}],"cols":[{"when":"flag"}],"cells":[[42.5]]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "fail-matrix-no-matching-row",
			graph: parLine(parNode("mx", events.NodeMatrix2D, `{"rows":[{"when":"amount > 100000"}],"cols":[{"when":"flag"}],"cells":[[1]]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-matrix-no-matching-col",
			graph: parLine(parNode("mx", events.NodeMatrix2D, `{"rows":[{"when":"amount >= 0"}],"cols":[{"when":"!flag"}],"cells":[[1]]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-matrix-cell-out-of-range",
			graph: parLine(parNode("mx", events.NodeMatrix2D, `{"rows":[{"when":"amount > 100000"},{"when":"amount >= 0"}],"cols":[{"when":"flag"}],"cells":[[1]]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-matrix-axis-condition-error",
			graph: parLine(parNode("mx", events.NodeMatrix2D, `{"rows":[{"when":"ghost > 1"}],"cols":[{"when":"flag"}],"cells":[[1]]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- code (Starlark shared subset) ---------------------------------------
		{
			name:  "code-starlark-arithmetic",
			graph: parLine(parNode("c", events.NodeCode, `{"code":"x = data['amount'] * 2\ny = x + 1\nq = data['amount'] / 8\nm = 7 % 2"}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "code-strings-comments-and-comparisons",
			graph: parLine(parNode("c", events.NodeCode, `{"code":"# derive a greeting\n\ns = data['name'] + '!'\nok = data['amount'] > 50"}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "code-reassignment",
			graph: parLine(parNode("c", events.NodeCode, `{"code":"x = 1\nx = x + 1"}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "code-integer-results-thread-into-expressions",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("c", events.NodeCode, `{"code":"x = data['amount'] * 2 + 1"}`),
				asn("calc", "m", "x % 3", "p", "x + 1", "d", "x / 2"),
				parNode("out", events.NodeOutput, ""),
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name:  "fail-code-empty",
			graph: parLine(parNode("c", events.NodeCode, `{"code":"   "}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- reason ---------------------------------------------------------------
		{
			name: "reason-accumulates-across-nodes",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("r1", events.NodeReason, `{"reasons":[
					{"when":"amount >= 100","code":"HIGH_AMOUNT","description":"Amount above threshold"},
					{"when":"amount > 100000","code":"HUGE","description":"Huge amount"}
				]}`),
				parNode("r2", events.NodeReason, `{"reasons":[
					{"when":"flag","code":"FLAGGED","description":"Flagged account"}
				]}`),
				parNode("out", events.NodeOutput, ""),
			),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "reason-no-match-empty-list",
			graph: parLine(parNode("r1", events.NodeReason, `{"reasons":[
				{"when":"amount > 100000","code":"HUGE","description":"Huge amount"}
			]}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "fail-reason-condition-unknown-name",
			graph: parLine(parNode("r1", events.NodeReason, `{"reasons":[
				{"when":"amount >= 100","code":"HIGH_AMOUNT","description":"Amount above threshold"},
				{"when":"ghost > 0","code":"GHOST","description":"Ghost"}
			]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name:  "fail-reason-empty-when",
			graph: parLine(parNode("r1", events.NodeReason, `{"reasons":[{"code":"X","description":"x"}]}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- manual review ----------------------------------------------------------
		{
			name: "manual-review-pass-through",
			graph: parLine(parNode("mr", events.NodeManualReview,
				`{"company_name":"'Corp-' + name","case_type":"'credit_review'","sla_days":3}`), ""),
			input: parInput,
			want:  domain.StatusCompleted,
		},
		{
			name: "manual-review-suspend",
			graph: parLine(parNode("mr", events.NodeManualReview,
				`{"company_name":"name","case_type":"'aml_alert'","sla_days":5,"suspend":true,"output_key":"review"}`), ""),
			input: parInput,
			want:  domain.StatusSuspended,
		},
		{
			name: "fail-manual-review-company-not-a-string",
			graph: parLine(parNode("mr", events.NodeManualReview,
				`{"company_name":"amount","case_type":"'credit_review'","sla_days":3}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-manual-review-case-type-unknown-name",
			graph: parLine(parNode("mr", events.NodeManualReview,
				`{"company_name":"name","case_type":"ghost","sla_days":3}`), ""),
			input: parInput,
			want:  domain.StatusFailed,
		},

		// --- pre-resolved provider buckets (predict / connect / ai) -----------------
		{
			name: "predict-pre-resolved-bucket",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("score", events.NodePredict, `{"model":"credit_pd","output":"pd"}`),
				asn("derive", "risk", "predict.pd.probability * 100"),
				parNode("out", events.NodeOutput, ""),
			),
			input: `{"amount": 100, "predict": {"pd": {"score": 1.4, "probability": 0.82}}}`,
			want:  domain.StatusCompleted,
		},
		{
			name: "connect-pre-resolved-bucket",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("bureau", events.NodeConnect, `{"connector":"experian","output":"bureau"}`),
				asn("derive", "fico", "connect.bureau.fico_score"),
				parNode("out", events.NodeOutput, ""),
			),
			input: `{"amount": 100, "connect": {"bureau": {"fico_score": 712, "utilization": 0.34}}}`,
			want:  domain.StatusCompleted,
		},
		{
			name: "ai-pre-resolved-bucket",
			graph: parChain(
				parNode("in", events.NodeInput, ""),
				parNode("draft", events.NodeAI, `{"agent":"adverse_action","output":"rationale","prompt":"Draft the rationale"}`),
				parNode("out", events.NodeOutput, `{"fields":["rationale","ai"]}`),
			),
			input: `{"amount": 100, "ai": {"rationale": "DTI above policy threshold."}}`,
			want:  domain.StatusCompleted,
		},

		// --- structural failures ----------------------------------------------------
		{
			name: "fail-dead-end-at-non-output-node",
			graph: events.Graph{
				Nodes: []events.Node{
					parNode("in", events.NodeInput, ""),
					parNode("a", events.NodeAssignment, `{"assignments":[{"target":"x","expr":"1"}]}`),
					parNode("out", events.NodeOutput, ""),
				},
				Edges: []events.Edge{{From: "in", To: "a"}},
			},
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-edge-to-unknown-node",
			graph: events.Graph{
				Nodes: []events.Node{
					parNode("in", events.NodeInput, ""),
					parNode("a", events.NodeAssignment, `{"assignments":[{"target":"x","expr":"1"}]}`),
				},
				Edges: []events.Edge{{From: "in", To: "a"}, {From: "a", To: "ghost"}},
			},
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-cycle-exceeds-node-bound",
			graph: events.Graph{
				Nodes: []events.Node{
					parNode("in", events.NodeInput, ""),
					parNode("a", events.NodeAssignment, `{"assignments":[{"target":"x","expr":"1"}]}`),
					parNode("b", events.NodeAssignment, `{"assignments":[{"target":"y","expr":"2"}]}`),
				},
				Edges: []events.Edge{{From: "in", To: "a"}, {From: "a", To: "b"}, {From: "b", To: "a"}},
			},
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-graph-has-no-input-node",
			graph: events.Graph{
				Nodes: []events.Node{
					parNode("a", events.NodeAssignment, `{"assignments":[{"target":"x","expr":"1"}]}`),
					parNode("out", events.NodeOutput, ""),
				},
				Edges: []events.Edge{{From: "a", To: "out"}},
			},
			input: parInput,
			want:  domain.StatusFailed,
		},
		{
			name: "fail-unknown-node-type",
			graph: events.Graph{
				Nodes: []events.Node{
					parNode("in", events.NodeInput, ""),
					parNode("w", events.NodeType("webhook"), ""),
					parNode("out", events.NodeOutput, ""),
				},
				Edges: []events.Edge{{From: "in", To: "w"}, {From: "w", To: "out"}},
			},
			input: parInput,
			want:  domain.StatusFailed,
		},
	}
}

// paritySplitGraph is in -> band(split condition) -> yes:approve / no:review -> out,
// optionally dropping the "no" edge (to fixture the missing-branch failure).
func paritySplitGraph(condition string, withNo bool) events.Graph {
	cfg, _ := json.Marshal(map[string]string{"condition": condition})
	g := events.Graph{
		Nodes: []events.Node{
			parNode("in", events.NodeInput, ""),
			parNode("band", events.NodeSplit, string(cfg)),
			parNode("approve", events.NodeAssignment, `{"assignments":[{"target":"approved","expr":"true"}]}`),
			parNode("review", events.NodeAssignment, `{"assignments":[{"target":"approved","expr":"false"}]}`),
			parNode("out", events.NodeOutput, ""),
		},
		Edges: []events.Edge{
			{From: "in", To: "band"},
			{From: "band", To: "approve", Branch: "yes"},
		},
	}
	if withNo {
		g.Edges = append(g.Edges, events.Edge{From: "band", To: "review", Branch: "no"})
	}
	g.Edges = append(g.Edges, events.Edge{From: "approve", To: "out"}, events.Edge{From: "review", To: "out"})
	return g
}

// buildParityExpect turns a Run into the serialized expectation the vitest replays.
func buildParityExpect(t *testing.T, run domain.Run) parityExpect {
	t.Helper()
	e := parityExpect{Status: string(run.Status), Trace: []parityTraceNode{}}
	for _, r := range run.Results {
		var out any
		if len(r.Output) > 0 {
			if err := json.Unmarshal(r.Output, &out); err != nil {
				t.Fatalf("unmarshal node %q output: %v", r.NodeID, err)
			}
		}
		e.Trace = append(e.Trace, parityTraceNode{NodeID: r.NodeID, Type: string(r.Type), Output: out})
	}
	switch run.Status {
	case domain.StatusCompleted:
		e.Output = run.Output
		if rc, ok := run.Output["reason_codes"].([]any); ok {
			e.ReasonCodes = rc
		}
	case domain.StatusFailed:
		e.FailedNode = run.FailedNode
		e.Error = run.Err
		e.ErrorContains = parityPositionSuffix.ReplaceAllString(run.Err, "")
	case domain.StatusSuspended:
		if run.Suspend == nil {
			t.Fatal("suspended run carries no suspend state")
		}
		e.Suspend = &paritySuspend{
			NodeID:      run.Suspend.NodeID,
			Record:      run.Suspend.Record,
			CompanyName: run.Suspend.Case.CompanyName,
			CaseType:    run.Suspend.Case.CaseType,
			SLADays:     run.Suspend.Case.SLADays,
		}
		if rc, ok := run.Suspend.Record["reason_codes"].([]any); ok {
			e.ReasonCodes = rc
		}
	}
	return e
}

// TestEngineParityFixtures generates the demo-parity battery from the REAL engine
// and asserts the committed fixture file matches what the engine computes today.
// UPDATE_PARITY_FIXTURES=1 rewrites the file; the default run fails loudly when the
// committed fixtures are stale (i.e. engine semantics moved without regenerating).
func TestEngineParityFixtures(t *testing.T) {
	file := parityFile{Readme: parityReadme, Cases: []parityCaseJSON{}}
	seen := map[string]bool{}
	for _, c := range parityCases() {
		if seen[c.name] {
			t.Fatalf("duplicate parity case name %q", c.name)
		}
		seen[c.name] = true
		input := map[string]any{}
		if err := json.Unmarshal([]byte(c.input), &input); err != nil {
			t.Fatalf("case %q input: %v", c.name, err)
		}
		run := domain.Execute(c.graph, input)
		if run.Status != c.want {
			t.Fatalf("case %q: engine returned status %q, the case declares %q (err %q)", c.name, run.Status, c.want, run.Err)
		}
		expect := buildParityExpect(t, run)
		if run.Status == domain.StatusFailed && expect.ErrorContains == "" {
			t.Fatalf("case %q: failed run yields an empty error_contains", c.name)
		}
		file.Cases = append(file.Cases, parityCaseJSON{Name: c.name, Graph: c.graph, Input: input, Expect: expect})
	}

	generated, err := json.MarshalIndent(file, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixtures: %v", err)
	}
	generated = append(generated, '\n')

	path := filepath.FromSlash(parityFixturesPath)
	if os.Getenv("UPDATE_PARITY_FIXTURES") == "1" {
		if err := os.WriteFile(path, generated, 0o644); err != nil {
			t.Fatalf("write fixtures: %v", err)
		}
		t.Logf("wrote %d parity cases to %s", len(file.Cases), path)
		return
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read committed fixtures (%v) — generate them with UPDATE_PARITY_FIXTURES=1 go test ./decision-engine/domain -run TestEngineParityFixtures", err)
	}
	if !bytes.Equal(committed, generated) {
		t.Fatalf("engine-parity fixtures are STALE: %s no longer matches what domain.Execute computes.\nRegenerate with UPDATE_PARITY_FIXTURES=1 go test ./decision-engine/domain -run TestEngineParityFixtures and re-run the web parity vitest.", path)
	}
}
